# Generated by Django 5.0.7 on 2024-08-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('answer_text', models.CharField(max_length=300)),
                ('topic_title', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=800)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('reversed_content', models.TextField(blank=True, null=True)),
                ('decipher_mode', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('quiz_questions', models.ManyToManyField(blank=True, to='Blog.quizquestion')),
            ],
        ),
    ]
